
spring:
  profiles:
    active: prod
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.baidu.springbootstarter.model
server:
  port: 80