spring:
  rabbitmq:
    host: 172.31.36.4
    port: 5672
    username: username
    password: password
    publisher-confirms: true
    virtual-host: /
    # 最大重试次数
    listener:
      simple:
        retry:
          max-attempts: 5
          # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          enabled: true
          # 重试间隔时间（单位毫秒）
          #spring.rabbitmq.listener.simple.retry.initial-interval: 5000
          # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
          default-requeue-rejected: false

  datasource:
    name: reserve_equipement
    type: com.alibaba.druid.pool.DruidDataSource

    # 使用druid数据源
    druid:
      url: jdbc:mysql://172.31.36.4:3306/reserve_equipement
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20